describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:5173');
    cy.get('#root button.ld-btn-login').click();
    cy.get('#login-username').click();
    cy.get('#login-username').type('josue2023');
    cy.get('#login-password').click();
    cy.get('#login-password').type('3117325j');
    cy.get('#root button.lgn-btn-submit').click();
     cy.wait(1500);
    cy.get('#root a[href="/Paqueteria"] span.sa-module-title').click();
    cy.get('#root div.paq-pagination-wrapper').click();
    cy.get('#root div:nth-child(1) > select.form-select').select('A');
    cy.get('#root div:nth-child(2) > select.form-select').select('101');
     cy.wait(1500);
    cy.get('#root i.bi-arrow-clockwise').click();
    cy.get('#root i.bi-list').click();
    cy.get('#root a[href="/Superadmin"] span').click();
     cy.wait(1500);
    cy.get('#root a[href="/visitas"] span.sa-module-title').click();
    cy.get('#root div:nth-child(1) > select.form-select').select('A');
    cy.get('#root div:nth-child(2) > select.form-select').select('101');
     cy.wait(1500);
    cy.get('#root i.bi-arrow-clockwise').click();
    cy.get('#root i.bi-list').click();
     cy.wait(1500);
    cy.get('#root a[href="/Superadmin"]').click();
    cy.get('#root a[href="/parqueaderos"] div.sa-module-icon-wrap').click();
    cy.get('#root button:nth-child(1) button.parq-btn-estado i.bi').click();
     cy.wait(1500);
    cy.get('button.swal2-cancel').click();
    cy.get('#root div:nth-child(2) > div.parq-filter-chips > button:nth-child(2)').click();
    cy.get('#root div:nth-child(2) > div.parq-filter-chips > button:nth-child(3)').click();
    cy.get('#root div.parq-filter-chips button:nth-child(4)').click();
     cy.wait(1500);
    cy.get('#root i.bi-list').click();
    cy.get('#root a[href="/Auditorias"]').click();
     cy.wait(1500);
    cy.get('#root div:nth-child(1) > select.form-select').select('INSERT');
    cy.get('#root div:nth-child(1) > select.form-select').select('UPDATE');
    cy.get('#root div:nth-child(1) > select.form-select').select('DELETE');
     cy.wait(1500);
    cy.get('#root i.bi-list').click();
     cy.wait(1500);
    cy.get('#root a[href="/LogErrores"] span').click();
    cy.get('#root button.le-btn-limpiar-log').click();
    cy.get('button.swal2-cancel').click();
    cy.get('#root i.bi-list').click();
     cy.wait(1500);
    cy.get('#root a[href="/visitas"]').click();
    cy.get('#root i.bi-arrow-left').click();
     cy.wait(1500);
    cy.get('#root button[title="Menú"]').click();
    cy.get('#root a[href="/Superadmin"]').click();
     cy.wait(1500);
    cy.get('#root a[href="/GestionUsuario"] div.sa-module-icon-wrap').click();
     cy.wait(1500);
    cy.get('#root select.form-select').select('2');
    cy.get('#root select.form-select').select('1');
    cy.get('#root select.form-select').select('3');
     cy.wait(1500);
    cy.get('#root div.gu-filter-chips button:nth-child(2)').click();
    cy.get('#root div.gu-filter-chips button:nth-child(3)').click();
    cy.get('#root button[title="Vista cuadricula"]').click();
     cy.wait(1500);
    cy.get('#root i.bi-list').click();
    cy.get('#root a[href="/Reportes"] span').click();
     cy.wait(1500);
    cy.get('#root div:nth-child(2) div.rpt-card-body div:nth-child(2) div.rpt-hbar-track div.rpt-hbar-fill').click();
    cy.get('#root div:nth-child(13) div.rpt-card-header').click();
    cy.get('#root button.rpt-hamburger').click();
     cy.wait(1500);
    cy.get('#root a[href="/Superadmin"] span').click();
    cy.get('#root a[href="/Reportes"] span.sa-module-title').click();
    cy.get('#root button[title="Volver"]').click();
     cy.wait(1500);
    cy.get('#root div.sa-modules-grid a[href="/Residentes"]').click();
    cy.get('#root button.res-btn-torres').click();
    cy.get('#root button[title="Ver apartamentos Torre B"] p:nth-child(2)').click();
    cy.get('#root button.res-torres-back').click();
     cy.wait(1500);
    cy.get('#root button[title="Ver apartamentos Torre C"] p:nth-child(2)').click();
    cy.get('#root i.bi-x-lg').click();
    cy.get('#root i.bi-list').click();
    cy.get('#root a[href="/Superadmin"]').click();
     cy.wait(1500);
    cy.get('#root div.sa-stat-card canvas').click();
    cy.get('#root div.sa-online-header').click();
    cy.get('#root button[title="Volver"]').click();
     cy.wait(1500);
    cy.get('#root a[href="/parqueaderos"] div.sa-stat-card-header').click();
    cy.get('#root button[title="Volver"]').click();
     cy.get('#root a[href="/Reportes"] span.sa-module-title').click();
    cy.get('#root div:nth-child(3) > div.rpt-card-body').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(3) > div.rpt-card-body > div.rpt-chart-container > canvas').click();
    cy.get('#root div.rpt-card-body > div.mt-3 > div:nth-child(1) > div.progress-header').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(5) div.rpt-card-header').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(7) th:nth-child(2)').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(8) tr:nth-child(2) td:nth-child(2)').click();
      cy.wait(1500);
    cy.get('#root div.rpt-pop-cards > div:nth-child(1)').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(11) div.rpt-card-header').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(12) div.rpt-card-header').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(13) div.rpt-card-header').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(14) div.rpt-card-header').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(1) > div.rpt-card-header').click();
      cy.wait(1500);
    cy.get('#root div:nth-child(1) > div.rpt-card-header').click();
    cy.get('#root button[title="Volver"]').click();
    cy.get('#root div.sa-modules-grid a[href="/Paqueteria"]').click();
    cy.get('#root i.bi-arrow-left').click();
    cy.get('#root a[href="/AreasComunes"] span.sa-module-title').click();
    cy.get('#root button.ac-btn-calendario').click();
    cy.get('#root div.ac-calendar-nav button:nth-child(3) i.bi').click();
    cy.get('#root div.ac-calendar-nav button:nth-child(3) i.bi').click();
    cy.get('#root i.bi-x-lg').click();
    cy.get('#root div.ac-pagination button:nth-child(3)').click();
    cy.get('#root button:nth-child(4)').click();
    cy.get('#root button[title="Volver"]').click();
    cy.get('#root i.bi-moon-stars-fill').click();
    cy.get('#root i.bi-sun-fill').click();
    cy.get('#root i.bi-list').click();
       
    cy.get('#root button.active').click();
    cy.get('#root a[href="/parqueaderos"] span.sa-module-title').click();
    cy.get('#root button:nth-child(1) button.parq-btn-estado').click();
    cy.get('#swal2-select').select('18');
    cy.get('button.swal2-confirm').click();
    cy.get('#root button.no-disponible button.parq-btn-estado i.bi').click();
    cy.get('div.swal2-popup').click();
    cy.get('#swal2-select').select('4');
    cy.get('button.swal2-confirm').click();
  })
})